on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - working-directory: hello_world_ui
        run: |
          yarn install
          yarn run test --ci
