on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker meta details
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{github.repository}}/hello_world
          flavor: |
            latest=auto
          tags: |
            type=semver,pattern={{version}}
            type=edge,branch=master
            type=sha

      - name: Build and push
        working-directory: hello_world_api
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          push: true
          tags: |
            bengotch/app:latest
